version: '3.9'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - .:/app    
      - /app/venv  
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:alpine 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./static:/app/static 
    ports:
      - "80:80"  
      - "443:443"  
    depends_on:
      - fastapi-app 
    stdin_open: true
    tty: true
